branch-defaults:
  master:
    environment: placelist-dev
    group_suffix: null
environment-defaults:
  placelist:
    branch: null
    repository: null
global:
  application_name: placelist
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.5
    running on 64bit Amazon Linux/2.8.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
